# Generated by Django 3.2.24 on 2024-02-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='username',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
